---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke
  template:
    metadata:
      labels:
        app: gke
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Hello Kubernetes! - GKE
